### ISSUE TITLE
Irregular `DnatRuleInValidPortID` error

### ISSUE THREAD

**Issue by macheins** [opentelekomcloud/terraform-provider-opentelekomcloud#1338]
# Terraform Version
1.0.5

# Affected Resource(s)
- `opentelekomcloud_nat_dnat_rule_v2`
- `opentelekomcloud_networking_port_v2`

# Terraform Configuration Files
```hcl
variable "network_id" {
  type = string
}

data "opentelekomcloud_vpc_subnet_v1" "this" {
  id = var.network_id
}

resource "opentelekomcloud_networking_port_v2" "this" {
  name       = "test"
  network_id = var.network_id
  fixed_ip {
    subnet_id = data.opentelekomcloud_vpc_subnet_v1.this.subnet_id
  }
}

resource "opentelekomcloud_nat_gateway_v2" "this" {
  name                = "test"
  spec                = "1"
  router_id           = data.opentelekomcloud_vpc_subnet_v1.this.vpc_id
  internal_network_id = data.opentelekomcloud_vpc_subnet_v1.this.id
}

variable "eip_id" {
  type = string
}

resource "opentelekomcloud_nat_dnat_rule_v2" "ssh" {
  floating_ip_id        = var.eip_id
  nat_gateway_id        = opentelekomcloud_nat_gateway_v2.this.id
  external_service_port = 80
  protocol              = "tcp"
  port_id               = opentelekomcloud_networking_port_v2.this.id
  internal_service_port = 80
}
```

# Steps to Reproduce
1. `terraform apply`

# Actual Behavior
```
Error: error creating Dnat: Bad request with: [POST https://nat.eu-de.otc.t-systems.com/v2.0/dnat_rules], error message: {"NeutronError": {"type": "DnatRuleInValidPortID", "detail": "", "message": "Port xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx is not a valid port."}}
```

# Important Factoids
Fails most of the time, but not always. Usually a second `terraform apply` succeeds. It could be a wait-for-status problem? In some cases, I had a seems-to-be-related error during `terraform destroy`.

**Comment by outcatcher** [comment]
Should be fixed by #1356, but still will need a retest after today's release.

**Comment by macheins** [comment]
Hey @outcatcher, problem persists for me with `1.26.0`.

**Comment by lego963** [comment]
@macheins can you recheck it?
```hcl
data "opentelekomcloud_vpc_subnet_v1" "this" {
  name = var.subnet_id
}

resource "opentelekomcloud_networking_port_v2" "this" {
  name       = "test"
  network_id = data.opentelekomcloud_vpc_subnet_v1.this.network_id
  fixed_ip {
    subnet_id = data.opentelekomcloud_vpc_subnet_v1.this.subnet_id
  }
}

resource "opentelekomcloud_nat_gateway_v2" "this" {
  name                = "test"
  spec                = "1"
  router_id           = data.opentelekomcloud_vpc_subnet_v1.this.vpc_id
  internal_network_id = data.opentelekomcloud_vpc_subnet_v1.this.id
}

resource "opentelekomcloud_vpc_eip_v1" "this" {
  publicip {
    type = "5_bgp"
  }
  bandwidth {
    name        = "test"
    size        = 8
    share_type  = "PER"
    charge_mode = "traffic"
  }
}

resource "opentelekomcloud_compute_instance_v2" "this" {
  name      = "tf-instance"
  flavor_id = var.flavor_id
  key_pair  = var.kp
  image_id  = var.image_id

  network {
    port = opentelekomcloud_networking_port_v2.this.id
  }
}

resource "opentelekomcloud_nat_dnat_rule_v2" "this" {
  floating_ip_id        = opentelekomcloud_vpc_eip_v1.this.id
  nat_gateway_id        = opentelekomcloud_nat_gateway_v2.this.id
  external_service_port = 80
  protocol              = "tcp"
  port_id               = opentelekomcloud_networking_port_v2.this.id
  internal_service_port = 80

  depends_on = [
    opentelekomcloud_compute_instance_v2.this
  ]
}
```

Tf log
```log
Plan: 5 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

opentelekomcloud_nat_gateway_v2.this: Creating...
opentelekomcloud_vpc_eip_v1.this: Creating...
opentelekomcloud_networking_port_v2.this: Creating...
opentelekomcloud_networking_port_v2.this: Creation complete after 8s [id=qwe]
opentelekomcloud_compute_instance_v2.this: Creating...
opentelekomcloud_vpc_eip_v1.this: Creation complete after 9s [id=qwe]
opentelekomcloud_nat_gateway_v2.this: Creation complete after 10s [id=qwe]
opentelekomcloud_compute_instance_v2.this: Still creating... [10s elapsed]
opentelekomcloud_compute_instance_v2.this: Still creating... [20s elapsed]
opentelekomcloud_compute_instance_v2.this: Still creating... [30s elapsed]
opentelekomcloud_compute_instance_v2.this: Creation complete after 30s [id=qwe]
opentelekomcloud_nat_dnat_rule_v2.this: Creating...
opentelekomcloud_nat_dnat_rule_v2.this: Creation complete after 9s [id=qwe]

Apply complete! Resources: 5 added, 0 changed, 0 destroyed.

C:\Users\rodgyrbu\Documents\terraform-tests>
```

**Comment by xopher-mc** [comment]
Issue still occurs!!

`
│ Error: Bad request with: [POST https://nat.eu-de.otc.t-systems.com/v2.0/dnat_rules], error message: {"NeutronError": {"type": "DnatRuleInValidPortID", "detail": "", "message": "Port f2237c68-695b-4014-bc60-a7d567611fa4 is not a valid port."}}
│
│   with opentelekomcloud_nat_dnat_rule_v2.dnat_1,
│   on main.tf line 114, in resource "opentelekomcloud_nat_dnat_rule_v2" "dnat_1":
│  114: resource "opentelekomcloud_nat_dnat_rule_v2" "dnat_1" {
│
╵`

Reapply then works

`opentelekomcloud_nat_dnat_rule_v2.dnat_1: Creation complete after 7s [id=043af61e-8695-4d45-a523-93df45fef8fb]`

My versions
```
terraform.exe --version
Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.28.1
```

**Comment by lego963** [comment]
@xopher-mc can you attach here your tf config?

**Comment by xopher-mc** [comment]
I've removed the 'secret info' 
[tfcodednatrule.zip](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/files/8388072/tfcodednatrule.zip)
